language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: python -m unittest discover
notifications:
  slack:
    secure: y291+qAIGrpBmZsY6ljKfHbEY/wMJHd86vJpMJhwbrksbV6IAyqixpMGyEHekjz8D7OD8Ccn39XY3aCxhEzDFy1zB6aRWTQ3nVqqsWvCOU/VxBmeP7W4rgXv4+CFTseuhrtYmu6HmR4L/YvMNllJueA4N6c4CgyqNbLa/Zf/gvIxsyrLlohuHGCrWes/sXvSuau2ix14TW/GS0Dh1Ts36S/Qc9Tgnsqfj4kb6pY0UNU4ws3me9zU18tmRE4bd0rztYz/jVs2IfgeD6x/p9ueRRYrw8hml44pAlXO0qz6u/l+r97DRp71Df3or0fD4gTS5Kjwl8eT/VXJe/KGLQaBC3IZpvH8eNshnEbzvsqC3ZoFGtNvyogX8Po166EdqLYgxDxWqfp8oxjXUWj2gNm0mE7lsEjXwWsbJ8M8YZ5FWhXFIV6/FEFJzzAJl8Vlg9q+YOzSpuMsYRL2GOTNyzWiNWhkFWfEkqCALc3E5j77e/JPOQNiSwyXgANw1biJUWh/mxjOdA5IuLJJx0Hwc77vW4oUUbpP9pbd8Ps6wPApl9TbdBKAUqDilH1mc9UudcENyaa5t5gP783Iz08X8x9ubih24e8Bb1U+7QiFGuPguqTacJvip30t22Jd7alkH8luY0Ovb99zTkaxeOFgIRxH0IxolRERfpFIR/JgPu+YrAk=
